spring:
  datasource:
    druid:
        url: jdbc:mysql://120.78.10.173:3306/PublicBoard
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root7777


server:
  port: 80

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mybatis:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
