spring:
  datasource:
    druid:
        url: jdbc:mysql://localhost:3306/publicboard
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root

server:
  port: 80

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql