spring:
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 1378113965@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: hplugrkpcoekbabb
    # 端口号465或587
    port: 465
    protocol: smtps
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:9999/publicboard
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: zoubingxi
      password: NyiK5iRR8F2wneTc

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB



server:
  port: 80

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


minio:
  endPoint: http://43.136.48.39:7778/
  accessKey: zoubingxi
  secretKey: bangbangtang
  bucket: publicboard

